/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ABadge: typeof import('ant-design-vue/es')['Badge']
    AButton: typeof import('ant-design-vue/es')['Button']
    AButtonGroup: typeof import('ant-design-vue/es')['ButtonGroup']
    AInput: typeof import('ant-design-vue/es')['Input']
    AProgress: typeof import('ant-design-vue/es')['Progress']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ASwitch: typeof import('ant-design-vue/es')['Switch']
    BooleanComponent: typeof import('./src/components/dynamicComponent/booleanComponent/booleanComponent.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    ProgressComponent: typeof import('./src/components/dynamicComponent/progressComponent/progressComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectMultiple: typeof import('./src/components/dynamicComponent/selectMultiple/selectMultiple.vue')['default']
    SelectSingle: typeof import('./src/components/dynamicComponent/selectSingleComponent/selectSingle.vue')['default']
    SingleField: typeof import('./src/components/single-field/Single-field.vue')['default']
    TestApp: typeof import('./src/components/testApp/testApp.vue')['default']
    TextComponent: typeof import('./src/components/dynamicComponent/textComponent/textComponent.vue')['default']
  }
}
